ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom_lidar
    base_link_frame: base_link
    world_frame: odom_lidar

    odom0: /kiss/odometry
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,
                  true,  true,  false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false