/**:
  ros__parameters:
    # Body params
    body_length: 0.375 # Length of the vehicle's body [m]
    body_width: 0.19 # Width of the vehicle's body [m]
    body_height: 0.225 # Height of the vehicle's body [m]
    body_density: 7850.0 # Density of the vehicle's body material, e.g., steel [kg/m^3]

    # Wheel params
    wheel_radius: 0.0425 # Radius of each wheel [m]
    wheel_width: 0.03 # Width of each wheel [m]
    wheel_density: 3230.4 # Density of the wheel material, e.g., rubber [kg/m^3]

    # Kinematics and dynamics params
    max_steering_angle: 0.6108652 # Maximum steering angle of the vehicle [rad]
    max_steering_angular_velocity: 1.570796 # Maximum steering angular velocity [rad/s]
    max_steering_effort: 1.0 # Maximum steering torque [Nm]
    max_velocity: 2.0 # Maximum wheel velocity [m/s]
    max_effort: 10.0 # Maximum wheel torque [Nm]